### ISSUE TITLE
Batch linking civi contacts to donor search?

### ISSUE THREAD

**Issue by zkrebs** [greenleafadvancement/com.greenleafadvancement.donorsearch#13]
Is it possible to do a search for a list of contacts and then link them to donor search profiles in a batch?

Also - what if we want to get the top 100 donors data into Civi - how would this extension help us accomplish that.

Thank you for your work - the extension as it exists is wonderful.

**Comment by guyiac** [comment]
For either scenario, you can import into the DonorSearch custom data fields as well as use the extension to do the lookups directly. I'm glad you are finding the extension helpful.
