### ISSUE TITLE
This extension uses a deprecated core function that is being removed

### ISSUE THREAD

**Issue by eileenmcnaughton** [greenleafadvancement/com.greenleafadvancement.donorsearch#14]
https://github.com/civicrm/civicrm-core/pull/17989

**Comment by MegaphoneJon** [comment]
Updating this issue to note that this extension is now broken on recent versions of CiviCRM as a result.

**Comment by guyiac** [comment]
> Updating this issue to note that this extension is now broken on recent versions of CiviCRM as a result.

Jon, thanks for bringing this to my attention. We are in the middle of some operational reorganization as far as responsibilities but I'll get someone on it. Thank you again and I hope you are well!

**Comment by deepak-srivastava** [comment]
@MegaphoneJon could you try master and see if that works. Deprecation was fixed in master https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/commit/3d35edd20a8a6339637222db1f57b035ba49cf05 but wasn't released.

@guyiac we need to test and release.

**Comment by deepak-srivastava** [comment]
New release v1.1.6 fixes the problem. Please reopen if you still see any issues.
