### ISSUE TITLE
cannot uninstall Navigation error

### ISSUE THREAD

**Issue by Stoob** [greenleafadvancement/com.greenleafadvancement.donorsearch#15]
Installed this extension back in Civi 4.7 and attempting to uninstall this extension in Civi 5.35 and getting this error.  Thoughts? @twomice 

```
CiviCRM_API3_Exception: "Expected one Navigation but found 0"

#0 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader.php(135): civicrm_api3("Navigation", "getvalue", (Array:3))
#1 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader.php(81): CRM_DonorSearch_Upgrader::changeNavigation("delete")
#2 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader/Base.php(288): CRM_DonorSearch_Upgrader->uninstall()
#3 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/donorsearch.civix.php(149): CRM_DonorSearch_Upgrader_Base->onUninstall()
#4 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/donorsearch.php(41): _donorsearch_civix_civicrm_uninstall()
#5 /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(60): donorsearch_civicrm_uninstall()
#6 /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(70): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), "uninstall")
#7 /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager.php(451): CRM_Extension_Manager_Module->onPreUninstall(Object(CRM_Extension_Info))
#8 /home/centos/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(163): CRM_Extension_Manager->uninstall((Array:1))
#9 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(526): CRM_Admin_Form_Extensions->postProcess()
#10 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(144): CRM_Core_Form->mainProcess()
#11 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(43): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#12 /home/centos/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#13 /home/centos/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#14 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(347): HTML_QuickForm_Page->handle("next")
#15 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(395): CRM_Core_Controller->run()
#16 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(140): CRM_Core_Page_Basic->edit(8, NULL)
#17 /home/centos/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(105): CRM_Core_Page_Basic->run()
#18 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(313): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#19 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:15))
#20 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:3))
#21 /home/centos/public_html/sites/all/modules/civicrm/drupal/civicrm.module(458): CRM_Core_Invoke::invoke((Array:3))
#22 /home/centos/public_html/includes/menu.inc(527): civicrm_invoke("admin", "extensions")
#23 /home/centos/public_html/index.php(21): menu_execute_active_handler()
#24 {main}

Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Expected one Navigation but found 0

Return to home page.
```

**Comment by twomice** [comment]
@Stoob Can you provide the version number of the extension on this site?

**Comment by Stoob** [comment]
1.1.6 @twomice

**Comment by twomice** [comment]
Note: similar error `Expected one Navigation but found 2` appears for me when installing 1.1.6 under civicrm 5.37.2.

**Comment by twomice** [comment]
@Stoob Since I'm seeing errors even when installing, I think we're going to have a hard time completely reproducing this. However, I think a patch like this one should work; what it does is to allow the possibility that the searched-for navigation entries (which the extension is trying to delete upon uninstall) don't exist; and then it only tries to delete them if they actually exist.

Would you mind trying this fix and seeing if it addresses your situation?

**Comment by twomice** [comment]
@Stoob Since I'm seeing errors even when installing, I think we're going to have a hard time completely reproducing this. However, I think a patch like this one should work; what it does is to allow the possibility that the searched-for navigation entries (which the extension is trying to delete upon uninstall) don't exist; and then it only tries to delete them if they actually exist.

Would you mind trying this fix and seeing if it addresses your situation?
[15.patch.txt](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/files/6657999/15.patch.txt)

**Comment by Stoob** [comment]
Error is gone.  The fun continues with this new error. 
`Expected one CustomGroup but found 0`

**Comment by twomice** [comment]
@Stoob Glad that helped. Can you post backtrace for this new error?

**Comment by Stoob** [comment]
`
CiviCRM_API3_Exception: "Expected one CustomGroup but found 0"

#0 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader.php(84): civicrm_api3("custom_group", "getvalue", (Array:3))
#1 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader/Base.php(288): CRM_DonorSearch_Upgrader->uninstall()
#2 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/donorsearch.civix.php(149): CRM_DonorSearch_Upgrader_Base->onUninstall()
#3 /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/donorsearch.php(41): _donorsearch_civix_civicrm_uninstall()
#4 /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(60): donorsearch_civicrm_uninstall()
#5 /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php(70): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), "uninstall")
#6 /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager.php(451): CRM_Extension_Manager_Module->onPreUninstall(Object(CRM_Extension_Info))
#7 /home/centos/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(163): CRM_Extension_Manager->uninstall((Array:1))
#8 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(526): CRM_Admin_Form_Extensions->postProcess()
#9 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(144): CRM_Core_Form->mainProcess()
#10 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(43): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#11 /home/centos/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#12 /home/centos/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#13 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(347): HTML_QuickForm_Page->handle("next")
#14 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(395): CRM_Core_Controller->run()
#15 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(140): CRM_Core_Page_Basic->edit(8, NULL)
#16 /home/centos/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(105): CRM_Core_Page_Basic->run()
#17 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(313): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#18 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:15))
#19 /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:3))
#20 /home/centos/public_html/sites/all/modules/civicrm/drupal/civicrm.module(458): CRM_Core_Invoke::invoke((Array:3))
#21 /home/centos/public_html/includes/menu.inc(527): civicrm_invoke("admin", "extensions")
#22 /home/centos/public_html/index.php(21): menu_execute_active_handler()
#23 {main}

Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
Expected one CustomGroup but found 0

Return to home page.

`

**Comment by twomice** [comment]
@Stoob Thanks. New patch attached here. Try this?
[15b.patch.txt](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/files/6658245/15b.patch.txt)

**Comment by Stoob** [comment]
`The website encountered an unexpected error. Please try again later`

No backtrace.  No debug. 

I think there is probably a syntax error in the patch 15b but I can't spot it.  Is there a method to just manually uninstall it via a mysql query?

**Comment by twomice** [comment]
Assuming the patch applied cleanly, there should be no syntax error.

Uninstalling manually is tricky. I hesitate to provide instructions in a public forum where they could lead less experienced folks to get themselves into trouble. 

Perhaps we should ping @colemanw or @MegaphoneJon who may be able to come up with a more elegant fix.

**Comment by colemanw** [comment]
Your patch looks ok to me.
FWIW, APIv4 can delete custom groups and fields at once and won't crash if they don't exist.

**Comment by MegaphoneJon** [comment]
@twomice This is the same fix I would do.  @Stoob that error is coming from Drupal - check (Drupal menu) **Reports » Recent Log Messages**.  If you can't even do that, try `SELECT * from watchdog ORDER BY wid DESC LIMIT 5` and you should see the extended error message.

**Comment by Stoob** [comment]
Thanks @MegaphoneJon I checked Drupal.  @twomice here is the error

`Error: Call to undefined method CRM_Core_BAO_Cache::deleteGroup() in CRM_DonorSearch_Upgrader->uninstall() (line 104 of /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader.php).`

**Comment by twomice** [comment]
Thanks @stoob for the error message. I'll try to update the patch. @colemanw do you have a recommendation for replacing `CRM_Core_BAO_Cache::deleteGroup('DonorSearch')` with something else?

**Comment by colemanw** [comment]
Not exactly but here's a clue. Before that function was removed the deprecated warning said:
```
CRM_Core_BAO_Cache::deleteGroup is deprecated and will be removed from core soon, use Civi::cache() facade or define cache group using hook_civicrm_container
```

Maybe just remove the line and put a comment about needing to refactor the caching used by this extension.

**Comment by twomice** [comment]
Thanks @colemanw . I guess there's no real harm in leaving the 'DonorSearch' group orphaned in the cache?

**Comment by twomice** [comment]
I'm going to assume the answer is "yes" to my [last question](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/issues/15#issuecomment-861815532). Working on a modified patch now. @Stoob

**Comment by twomice** [comment]
@Stoob Please try this patch, which implements [@colemanw 's suggestion](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/issues/15#issuecomment-861814056)

Note, this is meant as an ADDITIONAL patch to the two previously provided in this thread, and it assumes you have already applied those patches.

[15c.patch.txt](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/files/6664545/15c.patch.txt)

**Comment by Stoob** [comment]
Thank you but the saga continues.  With all 3 patches applied this is a new error.
`


CRM_Core_Exception:  is not of type String in /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php on line 1548
--
Exception trace
# | Function | Location
0 | CRM_Core_DAO::composeQuery('UPDATE civicrm_e…', Array, true) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php:1548
1 | CRM_Core_DAO::executeQuery('UPDATE civicrm_e…', Array) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/BAO/Extension.php:73
2 | CRM_Core_BAO_Extension::setSchemaVersion('com.greenleafadv…', null) | /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader/Base.php:247
3 | CRM_DonorSearch_Upgrader_Base-&gt;setCurrentRevision(null) | /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Upgrader/Base.php:296
4 | CRM_DonorSearch_Upgrader_Base-&gt;onUninstall() | /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/donorsearch.civix.php:149
5 | _donorsearch_civix_civicrm_uninstall() | /home/centos/public_html/civi.custom/baykeeper/extensions/com.greenleafadvancement.donorsearch/donorsearch.php:41
6 | donorsearch_civicrm_uninstall() | /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php:60
7 | CRM_Extension_Manager_Module-&gt;callHook(Object(CRM_Extension_Info), 'uninstall') | /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Module.php:70
8 | CRM_Extension_Manager_Module-&gt;onPreUninstall(Object(CRM_Extension_Info)) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Extension/Manager.php:451
9 | CRM_Extension_Manager-&gt;uninstall(Array) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php:163
10 | CRM_Admin_Form_Extensions-&gt;postProcess() | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Form.php:526
11 | CRM_Core_Form-&gt;mainProcess() | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php:144
12 | CRM_Core_StateMachine-&gt;perform(Object(CRM_Admin_Form_Extensions), 'next', 'Next') | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php:43
13 | CRM_Core_QuickForm_Action_Next-&gt;perform(Object(CRM_Admin_Form_Extensions), 'next') | /home/centos/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php:203
14 | HTML_QuickForm_Controller-&gt;handle(Object(CRM_Admin_Form_Extensions), 'next') | /home/centos/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php:103
15 | HTML_QuickForm_Page-&gt;handle('next') | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php:347
16 | CRM_Core_Controller-&gt;run() | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php:395
17 | CRM_Core_Page_Basic-&gt;edit(8, null) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php:140
18 | CRM_Core_Page_Basic-&gt;run() | /home/centos/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php:105
19 | CRM_Admin_Page_Extensions-&gt;run(Array, null) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:313
20 | CRM_Core_Invoke::runItem(Array) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:69
21 | CRM_Core_Invoke::_invoke(Array) | /home/centos/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:36
22 | CRM_Core_Invoke::invoke(Array) | /home/centos/public_html/sites/all/modules/civicrm/drupal/civicrm.module:458
23 | civicrm_invoke('admin', 'extensions') | /home/centos/public_html/includes/menu.inc:527
24 | menu_execute_active_handler() | /home/centos/public_html/index.php:21
25 | {main} | &nbsp;

`

**Comment by twomice** [comment]
@Stoob Sorry for all the whack-a-mole here. As alluded to earlier, since I can't install this extension locally (without some significant hoop-jumping due to cascading version compatibility), it's just hard for me  to test a real uninstall myself. 

So, on this latest error: it looks like this extension was built with `civix` some time ago. I've regenerated the boilerplate code for Upgrader/Base.php and *.civix.php, with the expectation this will work better.

Here's another patch that covers those changes:
[15d.patch.txt](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/files/6665494/15d.patch.txt)

**Comment by twomice** [comment]
BTW @Stoob , I've found a way to install under civicrm 5.37 (by just skipping out the code that was creating errors on install mentioned [earlier](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/issues/15#issuecomment-861740872)), and then I'm also able to uninstall successfully with an extension codebase that contains all of the above patches. This is encouraging, and hopefully you'll have good results with the latest patch.

**Comment by Stoob** [comment]
I don't know how to apply a patch with so many changes, sorry.  To your horror, now learn I have applying the patches manually via copy/paste. 

Can you please link to the latest whole file CRM/DonorSearch/Upgrader/Base.php so I can just drop it in my install in its entirety?

**Comment by twomice** [comment]
Sorry i had off site meetings this afternoon, will get you that file first thing in the morning @Stoob

**Comment by twomice** [comment]
@Stoob Changes for this ticket are now tracked in my branch https://github.com/twomice/com.greenleafadvancement.donorsearch/tree/15-cannot-uninstall

This file in particular is thus available at https://github.com/twomice/com.greenleafadvancement.donorsearch/blob/15-cannot-uninstall/CRM/DonorSearch/Upgrader/Base.php (Also note, patch 15d.patch.txt contained changes for donorsearch.civix.php, which are also reflected in that branch.)

**Comment by Stoob** [comment]
Sweet mercy.  It is uninstalled.  thank you so much!

**Comment by twomice** [comment]
Thanks Stuart. @guyiac do you think a PR with these changes would be useful -- i.e., is this project still active?

**Comment by deepak-srivastava** [comment]
With 1.2 release the uninstall should be clean. Please reopen if you still see any issues.
