### ISSUE TITLE
PHP8 compatibility - civix upgrade

### ISSUE THREAD

**Issue by mlutfy** [greenleafadvancement/com.greenleafadvancement.donorsearch#16]
Hi, can you upgrade civix, for PHP8 compatibility?

https://civicrm.org/blog/bgm/php-8-support-civicrm-extensions

I have removed the "reviewed" status for now, but will add it back once a new release is tagged.

Thanks!

**Comment by deepak-srivastava** [comment]
Hi @mlutfy civix upgrade and php8 compatibility has been addressed. Please update the status. 

Thanks.

**Comment by mlutfy** [comment]
@deepak-srivastava Please tag a release so that people can upgrade in-app.

**Comment by deepak-srivastava** [comment]
@mlutfy release has been tagged already - https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/releases/tag/1.2

**Comment by mlutfy** [comment]
@deepak-srivastava hmm the release failed to validate. The version in the info.xml should be `5.56` not `5.56.0`.

**Comment by deepak-srivastava** [comment]
Thanks @mlutfy. I've updated the tag and release.

**Comment by mlutfy** [comment]
@deepak-srivastava Excellent - thank you! I re-ran the scanner and updated the extension page on civicrm.org.

**Comment by deepak-srivastava** [comment]
@mlutfy great Thankyou! 
Are we going to see you in manchester again this time?

**Comment by mlutfy** [comment]
Yep! See you there!
