### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by MegaphoneJon** [greenleafadvancement/com.greenleafadvancement.donorsearch#19]
Hi all,

This extension says version 1.2 in the XML, but there's no 1.2 tag in Github, so civicrm.org/extensions doesn't know v1.2 exists.  Could you please tag a release?

**Comment by guyiac** [comment]
@deepak-srivastava

**Comment by deepak-srivastava** [comment]
@MegaphoneJon we were waiting to do some real tests with donorsearch accounts after some php8 fixes, but that didn't happen. Any chance you could test the master branch? If it works we 'll do the release.

Thanks

**Comment by MegaphoneJon** [comment]
I actually don't have a client using it - one installed it but I think they delayed their plans to implement.  This only came up because the Drupal "System Upgrade" module is saying there's a problem with how permissions are implemented if I upgrade to D10.  I didn't explore further.

**Comment by deepak-srivastava** [comment]
No worries. @guyiac helped me with the account. We've made some fixes and released v1.2.
