### ISSUE TITLE
Extension Review Request

### ISSUE THREAD

**Issue by universalhandle** [greenleafadvancement/com.greenleafadvancement.donorsearch#2]
@twomice requested that I review this extension for automated distribution. It seems our workflow related to extension review requests needs to be updated, as JIRA is largely shut down, even for the EXT project. In the meantime, I'll create a record of my assessment here.

Review was performed against tag v1.1.

| Category	| Criterion | Required for<br>*contributed*<br>extensions? | Assessment |
|------ | ----- | :-----------------------------: | --------------------- |
| Admin	| Code is licensed under AGPLv3+, GPLv2+, LGPLv2+, MIT/X11, or BSD-2c	| **Required**	| :+1: Manifest indicates AGPL-3.0. License is included in `LICENSE.txt`, which suggests the copyright is held by deb.monish <monish.deb@webaccessglobal.com>. |
| Admin	| Code is published on github.com 	| **Required**	| :+1: Code is [published on GitHub](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch) |
| Admin	| Extension name uses "org.civicrm.*" namespace	| No	| :man_shrugging: It does not, but this is not required for contributed extensions. |
| Admin	| Bus factor >= 2	| No	| :+1: Four developers have made significant contributions to this extension. Moreover, the original two developers have not contributed since 2017, but the project continues to be developed. |
| Admin	| Access to project is granted to infra team	| No	| :man_shrugging: Not evaluated. |
| Admin	| Release schedule is aligned with core	| No	| :man_shrugging: No, but this is not required for contributed extensions. |
| Coding	| All code complies with civicrm-core style guidelines	| No	| :man_shrugging: `civilint` found noncompliance in `donorsearch.php` and `CRM/DonorSearch/Upgrader/Base.php`. These are trivial, and compliance is not required for contributed extensions, anyway. |
| Coding	| Automated tests execute within 3 minutes (or less)	| No	| :man_shrugging: There do not appear to be any automated tests, though this is not a requirement for contributed extensions. |
| Coding	| All dependencies are at similar stage (Ex: A stable project should not depend on an experimental project)	| No	| :man_shrugging: The only apparent dependency is the DonorSearch API, which I can only assume is stable based on the "v2" in the URL. |
| Coding	| All strings are wrapped in ts()	| *Suggested*	| :man_shrugging: Inconsistent. See [donorsearch_civicrm_pageRun](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/blob/v1.1/donorsearch.php#L100), [DonorSearchNewWindow.js](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/blob/v1.1/js/DonorSearchNewWindow.js), and [Register.tpl](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/blob/v1.1/templates/CRM/DonorSearch/Form/Register.tpl) for some strings that could be internationalized. |
| Coding	| The project does not *override* `PHP` or `TPL` files from civicrm-core	| **Required**	| :+1: Found no overrides. |
| Coding	| The project does not modify the `SQL` schema of a standard civicrm-core table	| **Required**	| :+1: Found no modification of core tables. |
| Coding	| The project does not *conflict* with other official projects	| *Suggested*	| :man_shrugging: No apparent conflicts found. Anyway, this is not a requirement for contributed extensions. |
| Distribution	| The project is packaged as a CiviCRM Extension, Drupal Module, Backdrop Module, Joomla Extension, or WordPress plugin	| **Required**	| :+1: The project is packaged as a CiviCRM native extension. |
| Distribution	| The project has a stable version (1.0+; not alpha or beta)	| **Required**	| :+1: The project has a version of 1.1. |
| Distribution	| A demo site is provided	| *Suggested*	| :man_shrugging: No demo site is provided, but this is not a requirement for contributed extensions. |
| QA	| The project declares, on the in-app extension management screen, the nature of any changes it makes to existing data or functionality.	| **Required**	| :-1: The project should declare that it creates a new table `civicrm_ds_saved_search`. |
| QA	| The project functions in all CMS's (for CiviCRM Extension)	| *Suggested*	| :man_shrugging: Not evaluated. |
| QA	| An automated test suite is included	| *Suggested*	| :man_shrugging: No, but not required. |
| QA	| Project is periodically re-validated with newer versions of CiviCRM and compatibility updates are published	| No	| :man_shrugging: Not evaluated. |
| QA	| All patches are subjected to peer review	| No	| :man_shrugging: Judging by the number of commits and authors, and the lack of use of GitHub's pull request feature, I would surmise "no." However, this is not a requirement for contributed extensions. |
| QA	| All patches are subjected automated tests	| No	| :man_shrugging: There does not appear to be an automated testing suite. |
| Support	| Documentation is published	| *Suggested*	| :+1: Documentation is [published on GitHub](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch). |
| Support	| Issues are tracked in an open, public issue management system	| *Suggested*	| :+1:  GitHub issues are in use, and the extension manifest names the same as the support URL. |

## Items that Need Resolution before Extension Can Be Approved

* `info.xml` should be updated to declare that the extension creates a new table `civicrm_ds_saved_search`.
* The extension review guidelines state: "The extension must provide the promised functionality. Serious bugs and errors [...] are grounds for holding an extension back from automated distribution." Since the extension aims to allow users to perform wealth lookups and view the results, I need to see this in action before I can approve the extension. I performed a couple of lookups that yielded no results (i.e., per the README, the "Profile" field is empty). I gather that either the API key I was using is out of free lookups, or the people I was searching have no profiles -- I'll need your help getting results. Along these these lines, I discovered a major error which I think needs to be addressed before the extension should be distributed: when clicking "View DonorSearch Profile" button (i.e., visiting URL `/civicrm/view/ds-profile?cid=205`) on a contact with an empty "Profile" field, I get the following fatal error:
```
backTrace

#0 /path/to/site/root/sites/all/modules/civicrm/CRM/Core/Error.php(377): CRM_Core_Error::backtrace()
#1 /path/to/site/root/sites/default/files/civicrm/ext/com.greenleafadvancement.donorsearch/CRM/DonorSearch/Util.php(123): CRM_Core_Error::fatal("There is no DonorSearch profile")
#2 /path/to/site/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(275): CRM_DonorSearch_Util::viewProfile()
#3 /path/to/site/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:12))
#4 /path/to/site/root/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#5 /path/to/site/root/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#6 /path/to/site/root/includes/menu.inc(527): civicrm_invoke("view", "ds-profile")
#7 /path/to/site/root/index.php(21): menu_execute_active_handler()
#8 {main}
 Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
There is no DonorSearch profile
```
This should be addressed more gracefully, either by hiding the button in cases where there is no search profile, or displaying the empty result in a regular CiviCRM page rather than in a fatal-error style page.

## Strong Recommendations

* Don't store API key in plaintext. See the SparkPost extension for an example of [encrypting the password before saving](https://github.com/cividesk/com.cividesk.email.sparkpost/blob/master/CRM/Sparkpost.php#L30-L39). There is a decrypting example in the same file. You'll probably need to add an upgrade step, too, since there is presumably an existing user base with plain-text passwords in the DB.
* Link "See the [DonorSearch CiviCRM documentation](https://docs.civicrm.org/donorsearch/en/latest) for details" leads to a 500 error. I recommend either publishing documentation at that URL or removing the link.

## Recommendations

* On performing a search at /civicrm/ds/open-search?reset=1, I get: `Notice: Undefined variable: status in CRM_DonorSearch_API::throwDSError() (line 169 of /path/to/ext/com.greenleafadvancement.donorsearch/CRM/DonorSearch/API.php).` I don't know if that's related to the major error above, but addressing this may help identify the cause of that problem.
* Update `info.xml` with an accurate release date.
* Tag v1.1.1 to capture in your next release the updated release date, any changes you make in response to my recommendations above, and the nice README that is in master.

## To Consider

* I don't think I've seen the use of encoded HTML entities in `info.xml` in any extension but this one. This data could appear in multiple contexts, and HTML may not always be appropriate. It does not work, for instance, in `org.civicrm.extensionsui`.

**Comment by twomice** [comment]
Thanks @universalhandle Will address and follow-up here.

**Comment by twomice** [comment]
@universalhandle Thanks for the review. I've committed v.1.1.1  with the "Items that Need Resolution". I'll talk with the team about the other changes.

**Comment by twomice** [comment]
Err, correction: @universalhandle I've committed v1.1.2 with a couple more easy fixes, but still will talk to the team about the others.

**Comment by twomice** [comment]
FYI, we're moving ahead with more fixes in "Strong Recommendations", so not yet ready for a second round of review.

**Comment by universalhandle** [comment]
Cool, glad you found my recommendations useful!

**Comment by twomice** [comment]
@universalhandle I've addressed essentially all of the issues you mentioned now, in tag v1.1.3:

- encrypted storage for api key
- documentation links point to this repo's readme
- fixed typo bug causing `Notice: Undefined variable: status in CRM_DonorSearch_API::throwDSError()`
- removed html from info.xml
- corrected version and release date in info.xml

If you spot any further serious problems, just let me know. Thanks very much for your time!

**Comment by universalhandle** [comment]
Sorry it took so long to get back to you on this. With these updates, v1.1.3 looks good to distribute. Thanks!

I've flagged the extension for automated distribution. I note, however, that the Git URL for the [extension node](https://civicrm.org/node/7379/edit) is blank. That might cause you problems getting updates (or even the initially approved release) into the extensions UI. I didn't update it in case you left it blank intentionally as a means to delay release until you were ready.

**Comment by guyiac** [comment]
Thank you Frank!

**Comment by twomice** [comment]
Thanks Frank!  I've fixed the Git URL at https://civicrm.org/extensions/donorsearch-integration, so releases should start building automatically from existing tags within 24 hours.
