### ISSUE TITLE
Failed install: Expected one Navigation but found 24

### ISSUE THREAD

**Issue by andyburnsco** [greenleafadvancement/com.greenleafadvancement.donorsearch#3]
Upon trying to install, it gives this error. On WP.
![capture](https://user-images.githubusercontent.com/18341942/52806721-58b02800-304f-11e9-8190-14298e5420ea.PNG)

**Comment by twomice** [comment]
Thanks for the report, Andy. Please tell me:

1. What version of CiviCRM is this?
2. Does the extension appear to install correctly otherwise -- i.e., do things work as expected or does the installation simply fail to complete?

**Comment by andyburnsco** [comment]
Civi 5.8.2 and the extension simply fails, nothing is added.

**Comment by twomice** [comment]
Thank you, we'll look into it this week.

**Comment by twomice** [comment]
Hi @andyburnsco Oddly I'm not able to reproduce this error. I'm wondering if it might be caused by another extension. Can you tell me what other extensions are installed?  

Also one more bit of information that could help is a backtrace. You can enable this at Administer > System Settings > Debugging and Error Handling, where you can check "yes" for both options "Enable Debugging" and "Display Backtrace". If you can make that change and then uninstall/re-install the extension again, it should display several lines of technical detail along with the "Expected one Navigation but found 24" error message. Please copy that into a comment on this ticket if you can.

Thanks,
Allen

**Comment by andyburnsco** [comment]
Here are the extensions we are using.

All extensions are up-to-date:

    smartbe.be customisations (be.smartbe) version 1.0
    SparkPost integration (com.cividesk.email.sparkpost) version 1.3
    Cividesk Normalize (com.cividesk.normalize) version 1.0
    Stripe (com.drastikbydesign.stripe) version 5.2
    Geodata Filler (com.ginkgostreet.geofill) version 1.0.0-alpha1
    No Drill Down (coop.palantetech.nodrilldown) version 1.1.2
    Prevent users from overwriting their record (eu.tttp.noverwrite) version 1.3
    Summary Fields (net.ourpowerbase.sumfields) version 4.0.2
    CSV GUI Import to api (nz.co.fuzion.csvimport) version 1.3
    ExtendedReport (nz.co.fuzion.extendedreport) version 3.5
    Angular Profiles (org.civicrm.angularprofiles) version 4.7.31-1.1.2
    API v4 (org.civicrm.api4) version 4.1.0
    Contact Layout Editor (org.civicrm.contactlayout) version 1.3.1
    CiviDiscount (org.civicrm.module.cividiscount) version 3.7
    CiviCRM Multisite (org.civicrm.multisite) version 2.6
    twilio (org.civicrm.sms.twilio) version 1.2.1
    CiviVolunteer (org.civicrm.volunteer) version 4.7.31-2.3.1
    Collapse Comms and Demographics (uk.co.millertech.collapsecommsanddemographics) version 1.5
    Mosaico (uk.co.vedaconsulting.mosaico) version 1.1

This is the backtrace:

CiviCRM_API3_Exception: "Expected one Navigation but found 24"

#0 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php(190): civicrm_api3("Extension", "install", (Array:2))
#1 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(489): CRM_Admin_Form_Extensions->postProcess()
#2 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#3 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#4 /www/staging/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#5 /www/staging/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#6 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#7 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(401): CRM_Core_Controller->run()
#8 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(1, NULL)
#9 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#10 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#11 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:16))
#12 /www/staging/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#13 /www/staging/wp-content/plugins/civicrm/civicrm.php(1240): CRM_Core_Invoke::invoke((Array:3))
#14 /www/staging/wp-includes/class-wp-hook.php(286): CiviCRM_For_WordPress->invoke("")
#15 /www/staging/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters("", (Array:1))
#16 /www/staging/wp-includes/plugin.php(453): WP_Hook->do_action((Array:1))
#17 /www/staging/wp-admin/admin.php(224): do_action("toplevel_page_CiviCRM")
#18 {main}

**Comment by guyiac** [comment]
@andyburnsco if you'd like maybe we can set up a GoToMeeting and I can look deeper into your issue. Do you have access to the database and directory tree?

**Comment by andyburnsco** [comment]
Thanks @guyiac. I'll let you know when we are ready, right now a lot of other priorities are taking precedent :/
