### ISSUE TITLE
Contacts -> New Donor Search missing

### ISSUE THREAD

**Issue by joemcl** [greenleafadvancement/com.greenleafadvancement.donorsearch#9]
I've installed on Civi 5.18.3, Drupal 7.67. 
I've entered an API key I received from Donorsearch. 
I can see Donorsearch fields under Advanced Search -> Custom Fields. 
But I don't see Contacts -> New Donor Search to start a new search.
I re-installed with debugging and backtrace enabled, did not get an error message, made no difference, still don't see Contacts -> New Donor Search.

**Comment by joemcl** [comment]
Just discovering that Donorsearch does *social media matching* too so I'd *really* like to test this. 
Any help @guyiac @colemanw @MegaphoneJon @twomice @monishdeb @deepak-srivastava  in figuring out why I can't see Contacts -> New Donor Search is really appreciated, thanks!

**Comment by guyiac** [comment]
I'm not sure, but for now, what about under the Actions button for a particular contact?

**Comment by joemcl** [comment]
thanks @guyiac yeah thought of that and looked there - don't see New Donor Search or Donor Search as Action options...

![CiviActionsContactSearchResults](https://user-images.githubusercontent.com/3912434/69461978-a8352a00-0d2c-11ea-9d89-205b814ecd2c.jpeg)
![CiviActionsIndividualContact](https://user-images.githubusercontent.com/3912434/69461979-a8cdc080-0d2c-11ea-8d9c-d84a96710c0d.jpeg)

**Comment by joemcl** [comment]
Is there a URL link I can try? What's the standard URL for Contacts -> New Donor Search ? It's gonna be similar to `~/civicrm/ds/register?reset=1` right.

**Comment by joemcl** [comment]
So found `~/civicrm/ds/open-search` in the code [here](https://github.com/greenleafadvancement/com.greenleafadvancement.donorsearch/blob/6b4eaed029889c8368821e3324d218038da3725e/xml/Menu/donorsearch.xml), but I'm getting `Access Denied` at that link.

**Comment by joemcl** [comment]
thinking maybe it's that I'm using the 'wrong' API key? I signed up for a demo account, got the API key from that, registered it in the UI. Is there a different API key type I need to request for the CiviCRM integration? I'll also try to sign in in the UI with the demo account ID and PW that works on the website.

**Comment by guyiac** [comment]
So you don't see this:
![image](https://user-images.githubusercontent.com/9013199/69464377-31a82480-0d4c-11ea-8226-eb35ed2c845d.png)
 or this?
![image](https://user-images.githubusercontent.com/9013199/69464435-569c9780-0d4c-11ea-9233-050250c16cd8.png)

**Comment by guyiac** [comment]
Ahhh! You have to turn on the permission!!!!

I'm sorry, I always forget that. Need to add it to the documentation.

**Comment by joemcl** [comment]
aha. looked for that in Drupal Permissions. Didn't see anything. What is it called?

**Comment by joemcl** [comment]
aha - `Access DonorSearch` found it.

**Comment by joemcl** [comment]
OK so I think I'm good to go. Trying that search now...

![NewDonorSearch](https://user-images.githubusercontent.com/3912434/69464927-99527580-0d34-11ea-88d4-8574478aecb2.jpeg)

**Comment by joemcl** [comment]
closing, added #10
